allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': true
  '@scarf/scarf': true
  '@swc/core': true
  bcrypt: true
  esbuild: true
  protobufjs: true
minimumReleaseAgeExclude:
  - '@vkhang2stack/snowflake-id@1.0.2'
