export interface DomainConfig {
  VITE_API_URL: string;
  VITE_LOGTO_ENDPOINT: string;
  VITE_LOGTO_APP_ID: string;
  VITE_LOGTO_REDIRECT_URI: string;
  VITE_LOGTO_POST_LOGOUT_REDIRECT_URI: string;
}

// Build-time fallbacks from .env (baked in by Vite)
const defaults: DomainConfig = {
  VITE_API_URL: import.meta.env.VITE_API_URL || 'http://localhost:3000/api',
  VITE_LOGTO_ENDPOINT: import.meta.env.VITE_LOGTO_ENDPOINT || '',
  VITE_LOGTO_APP_ID: import.meta.env.VITE_LOGTO_APP_ID || '',
  VITE_LOGTO_REDIRECT_URI: import.meta.env.VITE_LOGTO_REDIRECT_URI || 'http://localhost:3000/callback',
  VITE_LOGTO_POST_LOGOUT_REDIRECT_URI: import.meta.env.VITE_LOGTO_POST_LOGOUT_REDIRECT_URI || 'http://localhost:3000',
};

// Live config object — populated before the app renders
export let domainConfig: DomainConfig = { ...defaults };

/**
 * Fetches /domain.json (generated by docker-entrypoint.sh from .env at runtime)
 * and merges non-empty values over the build-time defaults.
 * Must be called before ReactDOM.createRoot().
 */
export async function loadDomainConfig(): Promise<void> {
  try {
    const res = await fetch('/domain.json');
    if (!res.ok) return;
    const json: Partial<DomainConfig> = await res.json();
    // Only override keys that are explicitly set (non-empty) in domain.json
    const overrides = Object.fromEntries(Object.entries(json).filter(([, v]) => v !== '' && v != null)) as Partial<DomainConfig>;
    domainConfig = { ...defaults, ...overrides };
  } catch {
    // Keep build-time defaults if fetch fails (e.g. in local dev)
  }
}
