export interface DomainConfig {
  VITE_API_URL: string;
  VITE_LOGTO_ENDPOINT: string;
  VITE_LOGTO_APP_ID: string;
  VITE_LOGTO_REDIRECT_URI: string;
  VITE_LOGTO_POST_LOGOUT_REDIRECT_URI: string;
  VITE_FIREBASE_API_KEY: string;
  VITE_FIREBASE_AUTH_DOMAIN: string;
  VITE_FIREBASE_PROJECT_ID: string;
  VITE_FIREBASE_STORAGE_BUCKET: string;
  VITE_FIREBASE_MESSAGING_SENDER_ID: string;
  VITE_FIREBASE_APP_ID: string;
  VITE_FIREBASE_VAPID_KEY: string;
}

// Build-time fallbacks from .env (baked in by Vite)
const defaults: DomainConfig = {
  VITE_API_URL: import.meta.env.VITE_API_URL || 'http://localhost:3000/api',
  VITE_LOGTO_ENDPOINT: import.meta.env.VITE_LOGTO_ENDPOINT || '',
  VITE_LOGTO_APP_ID: import.meta.env.VITE_LOGTO_APP_ID || '',
  VITE_LOGTO_REDIRECT_URI: import.meta.env.VITE_LOGTO_REDIRECT_URI || 'http://localhost:3000/callback',
  VITE_LOGTO_POST_LOGOUT_REDIRECT_URI: import.meta.env.VITE_LOGTO_POST_LOGOUT_REDIRECT_URI || 'http://localhost:3000',
  VITE_FIREBASE_API_KEY: import.meta.env.VITE_FIREBASE_API_KEY || '',
  VITE_FIREBASE_AUTH_DOMAIN: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN || '',
  VITE_FIREBASE_PROJECT_ID: import.meta.env.VITE_FIREBASE_PROJECT_ID || '',
  VITE_FIREBASE_STORAGE_BUCKET: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET || '',
  VITE_FIREBASE_MESSAGING_SENDER_ID: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID || '',
  VITE_FIREBASE_APP_ID: import.meta.env.VITE_FIREBASE_APP_ID || '',
  VITE_FIREBASE_VAPID_KEY: import.meta.env.VITE_FIREBASE_VAPID_KEY || '',
};

// Live config object — populated before the app renders
export let domainConfig: DomainConfig = { ...defaults };

// sessionStorage key holding the last-fetched domain.json overrides, so a
// transient network failure on a later reload (same tab) falls back to the
// last known-good runtime config instead of silently reverting to build-time
// defaults (e.g. the wrong Firebase project).
const CACHE_KEY = 'domain-config';

function readCache(): Partial<DomainConfig> | null {
  try {
    const raw = sessionStorage.getItem(CACHE_KEY);
    return raw ? (JSON.parse(raw) as Partial<DomainConfig>) : null;
  } catch {
    return null;
  }
}

function writeCache(overrides: Partial<DomainConfig>): void {
  try {
    sessionStorage.setItem(CACHE_KEY, JSON.stringify(overrides));
  } catch {
    // Ignore quota/availability errors (e.g. private browsing) — caching is best-effort.
  }
}

let loadPromise: Promise<void> | undefined;

/**
 * Fetches /domain.json (generated by docker-entrypoint.sh from .env at runtime),
 * merges non-empty values over the build-time defaults, and caches the result in
 * sessionStorage so a later reload in the same tab can fall back to it if the
 * fetch fails. Must be called before ReactDOM.createRoot().
 *
 * Idempotent: concurrent/repeat calls (e.g. from multiple modules initializing)
 * share the same in-flight fetch instead of issuing duplicate requests.
 */
export function loadDomainConfig(): Promise<void> {
  if (!loadPromise) {
    loadPromise = (async () => {
      try {
        const res = await fetch('/domain.json');
        if (!res.ok) throw new Error(`GET /domain.json: ${res.status}`);
        const json: Partial<DomainConfig> = await res.json();
        // Only override keys that are explicitly set (non-empty) in domain.json
        const overrides = Object.fromEntries(Object.entries(json).filter(([, v]) => v !== '' && v != null)) as Partial<DomainConfig>;
        domainConfig = { ...defaults, ...overrides };
        writeCache(overrides);
      } catch {
        // Fetch failed (e.g. offline, or no domain.json in local dev) — fall back to
        // the last successfully fetched config for this tab session, if any.
        const cached = readCache();
        if (cached) domainConfig = { ...defaults, ...cached };
      }
    })();
  }
  return loadPromise;
}
