export enum ErrorCode {
  SUCCESS = 0,
  UNKNOWN_ERROR = 1,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  INTERNAL_SERVER_ERROR = 500,
  CHANNEL_NOT_LINKED_OR_ENABLED = 1001,
  INVALID_ZALO_WEBHOOK_SIGNATURE = 1002,
  ZALO_WEBHOOK_VERIFICATION_FAILED = 1003,
  ZALO_WEBHOOK_REGISTRATION_FAILED = 1004,
  CHANNEL_NOT_SUPPORTED = 1005,
}
