import { QueryCache, QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { createRouter, RouterProvider } from '@tanstack/react-router';
import { AxiosError } from 'axios';
import { StrictMode } from 'react';
import ReactDOM from 'react-dom/client';

import { toast } from 'sonner';
import { getResponseCode, RESPONSE_CODE_MESSAGES, ResponseCode } from '@/lib/response-codes';
import { useAuthStore } from '@/stores/authStore';
import { handleServerError } from '@/utils/handle-server-error';
import { FontProvider } from './context/font-context';
import { Theme, ThemeProvider } from './context/theme-context';
import './index.css';
import { loadDomainConfig } from './lib/domain-config';
// Generated Routes
import { routeTree } from './routeTree.gen';

// When a hashed chunk no longer exists after a new deploy, reload once to get fresh index.html
window.addEventListener('vite:preloadError', () => {
  const key = 'vite-preload-reload-at';
  const last = Number(sessionStorage.getItem(key) ?? 0);
  if (Date.now() - last > 10_000) {
    sessionStorage.setItem(key, String(Date.now()));
    window.location.reload();
  }
});

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      retry: (failureCount, error) => {
        // eslint-disable-next-line no-console
        if (import.meta.env.DEV) console.log({ failureCount, error });

        if (failureCount >= 0 && import.meta.env.DEV) return false;
        if (failureCount > 3 && import.meta.env.PROD) return false;

        return !(error instanceof AxiosError && [401, 403].includes(error.response?.status ?? 0));
      },
      refetchOnWindowFocus: import.meta.env.PROD,
      staleTime: 10 * 1000, // 10s
    },
    mutations: {
      onError: (error) => {
        handleServerError(error);

        if (error instanceof AxiosError) {
          if (error.response?.status === 304) {
            toast.error('Content not modified!');
          }
        }
      },
    },
  },
  queryCache: new QueryCache({
    onError: (error) => {
      if (error instanceof AxiosError) {
        const responseCode = getResponseCode(error);
        const status = error.response?.status;

        const isUnauthorized = responseCode === ResponseCode.UnAuthorization || responseCode === ResponseCode.TokenNotFound || status === 401;
        const isServerError = responseCode === ResponseCode.InternalServerError || status === 500;
        const isForbidden = responseCode === ResponseCode.Forbidden || status === 403;

        if (isUnauthorized) {
          toast.error(RESPONSE_CODE_MESSAGES[ResponseCode.UnAuthorization]);
          useAuthStore.getState().auth.reset();
          const redirect = `${router.history.location.href}`;
          router.navigate({ to: '/sign-in', search: { redirect } });
        }
        if (isServerError) {
          toast.error(RESPONSE_CODE_MESSAGES[ResponseCode.InternalServerError]);
          router.navigate({ to: '/500' });
        }
        if (isForbidden) {
          router.navigate({ to: '/403' });
        }
      }
    },
  }),
});

// Create a new router instance
const router = createRouter({
  routeTree,
  context: { queryClient },
  defaultPreload: 'intent',
  defaultPreloadStaleTime: 0,
});

// Register the router instance for type safety
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}
// Load runtime config from /domain.json (generated by docker-entrypoint.sh),
// then render with values from domainConfig instead of baked-in build-time env vars.
(async () => {
  await loadDomainConfig();

  const rootElement = document.getElementById('root')!;
  if (!rootElement.innerHTML) {
    const root = ReactDOM.createRoot(rootElement);
    root.render(
      <StrictMode>
        <QueryClientProvider client={queryClient}>
          <ThemeProvider defaultTheme={Theme.Light} storageKey="vite-ui-theme">
            <FontProvider>
              <RouterProvider router={router} />
            </FontProvider>
          </ThemeProvider>
        </QueryClientProvider>
      </StrictMode>,
    );
  }
})();
